shell = "zsh -c '{}'"

[[items]]
file = "~/.config/kitty/kitty.conf"
template = "kitty"
hook = "kill -SIGUSR1 $(pgrep kitty)"

[[item]]
file = "~/.config/zathura/zathurarc"
template = "zathura"
subtemplate = "recolor"

[[item]]
file = "~/.config/ags/colors.scss"
template = "ags"
rewrite = true
hook = "ags quit -i launcher"

[[item]]
file = "~/.config/hypr/hyprland.conf"
template = "hyprland"

[[item]]
file = "~/.config/nvim/lua/mmed/plugins/ui.lua"
template = "nvim-colors"
start = "			-- flavours start"
end = "			-- flavours end"

[[item]]
file = "~/.config/nvim/lua/mmed/plugins/colors.lua"
template = "nvim"
rewrite = true
hook = "color-nvim"

[[item]]
file = "~/.config/kando/config.json"
template = "kando"
rewrite = true

[[item]]
file = "~/.config/cava/config"
template = "cava"
rewrite = true
hook = "pkill -USR2 cava"

[[item]]
file = "~/.Xresources"
template = "Xresources"
rewrite = true
hook = "xrdb -load ~/.Xresources"

[[item]]
file = "~/.config/hyprpanel/config.json"
template = "hyprpanel"
rewrite = true
hook = "hyprpanel -q;hyprpanel&"
